Do not need to specify the number of groups prior to training. 
The Mean Shift algorithm finds clusters on its own. For this reason, it is even more of an "unsupervised" machine learning algorithm than K-Means.

                                        radius = bandwidth


In [1]:
import numpy as np
from sklearn.cluster import MeanShift
import matplotlib.pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
from matplotlib import style
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
style.use('ggplot')

#interactive plotting in separate window
%matplotlib qt 

In [2]:
centers = [[1,1,1],[5,5,5],[3,10,10]]

#making number of sample using make_blobs of sklearn
X, _ = make_blobs(n_samples = 1000, centers = centers, cluster_std = 1.5)
ms = MeanShift()
ms.fit(X)
labels = ms.labels_
cluster_centers = ms.cluster_centers_

In [3]:
print(cluster_centers)
# np.unique returns an array of unique elements in the input array. 
# The function can be able to return a tuple of array of unique vales and an array of associated indices.
n_clusters_ = len(np.unique(labels))
print("Number of estimated clusters:", n_clusters_)

colors = 10*['r','g','b','c','k','y','m']
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

for i in range(len(X)):
    ax.scatter(X[i][0], X[i][1], X[i][2], c=colors[labels[i]], marker='o')

ax.scatter(cluster_centers[:,0],cluster_centers[:,1],cluster_centers[:,2],
            marker="x",color='k', s=150, linewidths = 5, zorder=10)

plt.show()

[[ 4.86674927  5.09919217  5.04971434]
 [ 1.05284251  1.18634265  1.12361266]
 [ 3.08584894 10.06250693  9.97360721]]
Number of estimated clusters: 3
